### ISSUE TITLE
Error: The module was compiled against a different Node.js version using NODE_MODULE_VERSION 48.

### ISSUE THREAD

**Issue by nukeop** [emersion/mpris-service#11]
Hi, I'm getting the following error after trying to use mpris-service and running my program:

```
Error: The module '<project>/node_modules/dbus/build/Release/dbus.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (<project>/node_modules/dbus/lib/dbus.js:3:13)
    at Object.<anonymous> (<project>/node_modules/dbus/lib/dbus.js:148:3)

```

I'm trying to use it in an Electron program. Would you happen to know how to recompile dbus.node to work with my version of node (6.10.1)? Or maybe there's a different fix for this issue?

**Comment by emersion** [comment]
Maybe `npm rebuild dbus`?

**Comment by nukeop** [comment]
Nope, the problem still occurs. Reinstalling dbus manually doesn't help either.

**Comment by emersion** [comment]
Okay, maybe a `dbus` upgrade to `v1` can fix it.

**Comment by fcastilloec** [comment]
The package `electron-rebuild` can fix this issue. You can run `./node_modules/.bin/electron-rebuild` or if you have it installed globally, just `electron-rebuild` and it will recompile the module for your current version of node.js
It's weird that the published version of `dbus` is compiled against `NODE_MODULE_VERSION 54` which is not an LTS release and it's not even in the list of [previous releases](https://nodejs.org/en/download/releases/).
The `dbus` package should be updated to compile either with v6, the current LTS, or v8 which will become LTS on October 2018 (less than two months from now)

**Comment by nukeop** [comment]
I can confirm that this fixes the above problem.
However, I still can't see the program being registered and it doesn't show up with the rest of mpris-supporting programs, but that's probably another issue altogether.

**Comment by fcastilloec** [comment]
@nukeop the developers seem busy at the moment, but since you created this issue, you could close it yourself.
