### ISSUE TITLE
CanGoPrevious & CanGoNext variable updating but mpris is not

### ISSUE THREAD

**Issue by Superjo149** [emersion/mpris-service#13]
When setting the value after the initial value is set, the values change but the mpris widget doesn't change anymore.

**Comment by emersion** [comment]
Can you try adding these properties to https://github.com/emersion/mpris-service/blob/cdd02bbef4585f8259b029caf912f667e220bcbf/index.js#L231 and see if it solves the issue?

**Comment by Superjo149** [comment]
Still no, I'm setting these first before changing **cangonext** and it still wont change.

**Initital values**
<pre>

        player.playbackStatus = 'Stopped';
        player.canEditTracks = false;
        player.canSeek = false;
        player.canGoPrevious = false;
        player.canGoNext = false;
        player.shuffle = false;
        player.canControl = true;
        player.loopStatus = "None";
        player.rate = 1.0;
</pre>

Values when logging, are changing, just not the widget.
*In console, first values are the old ones.
http://imgur.com/a/O6Kef
