### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by emersion** [emersion/mpris-service#20]
Now that we have tests, CI would be nice.

**Comment by fcastilloec** [comment]
I recommend using Travis as CI.

I'm just very excited about all the reset changes and progress. Looking forward to the end result!

**Comment by emersion** [comment]
Other options include https://builds.sr.ht/ which is somewhat nicer to use than Travis.

Though, I'm not feeling strongly about the CI platform we choose, what matters is having CI :)

**Comment by acrisci** [comment]
This is my working [travis.yml](https://github.com/acrisci/node-dbus-next/blob/master/.travis.yml) for dbus-next. It should be exactly the same for this project if you use travis.

**Comment by emersion** [comment]
Ah, nice

Fixed in https://github.com/emersion/mpris-service/commit/7f0182483d94950ac4cde4605361ff64917a66e9

However builds fail: https://travis-ci.org/emersion/mpris-service/jobs/504305093

**Comment by acrisci** [comment]
fixed in #28
