### ISSUE TITLE
Sending/Receiving negative numbers

### ISSUE THREAD

**Issue by fcastilloec** [emersion/mpris-service#27]
I usually use [playerctl](https://github.com/acrisci/playerctl) to control and test my MPRIS applications. I recently switched to the new `mpris-service` and `dbus-next` and all the negative values I'm receiving are a bit complement of the actual value.
Here's a simple sample code:
```js
const mpris = require('mpris-service');
const mprisPlayer = mpris({
  name: 'test',
  identity: 'test',
  supportedInterfaces: ['player'],
  desktopEntry: 'test',
});
mprisPlayer.on('seek', (seek) => {
  console.log(`Seek ${seek / 1e6} sec`);
});
```
Using the following command `playerctl position 30-` you'll see the following output on the console:
```
Seek -9223372036824.775 sec
```
While sending `playerctl position 30+` returns the right number.

As a workaround, I've set a complement inside the `seek` event: `if (seek < 0) seek = ~seek;`

I think this should have been solved on `dbus-next` v0.3.2, there's some reference there regarding negative numbers and using Long internally, but this module is using the latest version so I don't know what's going on.

**Comment by acrisci** [comment]
Yeah this was fixed here: https://github.com/acrisci/node-dbus-next/commit/0611a9ce41e6680b8d4adab0cd2971fe8af63be4 and will be included in the next version of mpris-service.

**Comment by acrisci** [comment]
Working on finalizing the dbus-next api now and will release here after that is good.
