### ISSUE TITLE
Use pure JS node-dbus ?

### ISSUE THREAD

**Issue by YurySolovyov** [emersion/mpris-service#6]
If all required features are there, I think it would be nice to switch into pure JS version to improve portability.

**Comment by emersion** [comment]
You mean, switch to https://github.com/sidorares/node-dbus?

Yeah, that would be much better. What's more, the currently used dbus implementation makes fixing bugs like #1 very difficult.

**Comment by emersion** [comment]
Service implementation example: https://github.com/sidorares/node-dbus/blob/master/examples/service/server2.js

**Comment by YurySolovyov** [comment]
I'd looked into this, but I have 0 experience with dbus and this repo does not have any tests, so I either need some guidance or need to add some tests

**Comment by emersion** [comment]
I think the first thing to do would be to describe the [`org.mpris.MediaPlayer2`](http://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html) interface with an object like this: https://github.com/sidorares/node-dbus/blob/master/examples/service/server2.js#L15

Letters used are data types (yeah, it kind of sucks), here is the spec: https://dbus.freedesktop.org/doc/dbus-specification.html#type-system

It seems that for methods, the last item in the types list is the return value. All others are arguments.

Then, we'll need to implement `org.mpris.MediaPlayer2` with JS functions. d-feet is a great tool to debug this.

Tests are a very good idea, but I don't really know how to implement them. Created an issue for that: #7

**Comment by YurySolovyov** [comment]
actually, that module is not purely native too, instead, it uses `abstract-socket` as optional dependency(or claims to).

see https://github.com/sidorares/node-dbus/issues/92

**Comment by acrisci** [comment]
Yeah looked over the code and what it would take to patch the current dbus library, and I think it's easier just to write it out. Working on this now.

**Comment by acrisci** [comment]
I found a bug in 0.2.5 of dbus-native that won't handle functions that return nothing, but it's fixed in the master branch.

**Comment by acrisci** [comment]
Now I have found that the `org.freedesktop.DBus.Properties` interface is not fully implemented and not overridable in the dbus-native project which is a big problem.

**Comment by emersion** [comment]
Thanks for looking into this! Indeed we do need a full `org.freedesktop.DBus.Properties` implementation, do you know if a big piece of it is missing or if it's easy to add it?

**Comment by acrisci** [comment]
There's an internal implementation of the properties interface that's different from the exported interface implementation. There's no way to emit events on the internal implementation, so we can't emit `PropertiesChanged` which is required to make playerctl work.

The `Set` method of properties is not implemented.

There's no way to make a property readonly either.

I'll do some probing PRs and see if the maintainer has a will to make this work.

**Comment by acrisci** [comment]
Another problem with dbus-native is it has a very unusual and undocumented variant object format you'd need to write a converter for.

The current library node-dbus is no better. It completely ignores the types of the properties. There is no way to represent "1.0" as anything other than a byte which is needed for volume and rate.

I'm beginning to think the best way to fix this is to just write your own dbus service in C because there's not a good library for writing the services in node.

**Comment by acrisci** [comment]
Hey, I'm redesigning the dbus-native service interface so it can work for this project.

https://github.com/acrisci/node-dbus-next

See a working example [here](https://github.com/acrisci/node-dbus-next/tree/master/examples/new-service).

Let me know what you think.

**Comment by emersion** [comment]
Looks great! Keep up the good work!

**Comment by martpie** [comment]
Can I say I love you guys?

**Comment by acrisci** [comment]
:sunglasses:

**Comment by martpie** [comment]
@emersion Can we expect a release soon?

**Comment by emersion** [comment]
Yes. I wonder if this should be a new major release. @acrisci, thoughts?

**Comment by acrisci** [comment]
Yes definitely a new release. I'm pretty confident it works ok.

Electron integration is what worries me a little. I've tested it in the Electron sample app and it works fine. However, I can't get it to work in [GPMDP](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-). I think they might have some security thing that's disabling the node interfaces. I'm still looking into it.

**Comment by acrisci** [comment]
Ok just figured it out. They use an invalid interface name (includes the `-` character). Once I change those to `_` it works fine. Going to add some validation for that.

**Comment by emersion** [comment]
Nice. I'll wait a little to get your fix in.

**Comment by acrisci** [comment]
@emersion I have a branch of GPMDP with mpris functional for playerctl. Ready for release :+1: .

**Comment by emersion** [comment]
2.0 released! :tada:

Thanks again for your hard work!

**Comment by acrisci** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/pull/3513

**Comment by martpie** [comment]
@acrisci When trying to use `mpris-service` in Electron 4, I get an error with `BigInt`

```
A JavaScript error occured in the main process
Uncaught Exception:
TypeError: JSBI.BigInt is not a function
```

I am a bit confused because Electron 4 is based on Node 10 so everything "should" work, any idea?

**Comment by acrisci** [comment]
@martpie can you open a new issue with some more information on the error?
