### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by emersion** [emersion/mpris-service#7]
Tests would be nice to have, but how to implement them?

**Comment by YurySolovyov** [comment]
It really depends on what module does and how can we make sure that it does what it should.
E.g. for databases that would be check that inserted rows are persisted and can be queried.
Sorry if this kind of obvious, maybe you can give some insight on how can we for example make sure that our service sets proper variables or keeps some state.

Another approach would be to just mock everything and test against pure mock, but this is kind of self-delusion.

**Comment by emersion** [comment]
This service just offers:
* Data about the current playback state
* Methods to change the playback state

So we would need a dbus client which checks that returned data is correct and that the right methods are called with the right arguments. We could do this with the dbus module directly.

**Comment by YurySolovyov** [comment]
mm, isn't calling 
> Methods to change the playback state

would change
> Data about the current playback state

?

**Comment by emersion** [comment]
No, because calling methods are _requests_ to change the playback state, and apps using the service must process those requests and explicitly update playback state themselves. Apps can reject some requests (like clicking "Next" when there is no more tracks in the play queue).

**Comment by emersion** [comment]
So a typical workflow is:
* A track is playing, a "Pause" button is shown
* The user clicks the "Pause" button
* The client calls the PlayPause dbus method
* The app accepts this request and pauses the current track
* The app updates the service state to notify that the current track is paused
* The client figures out that the current track is now paused
* The client changes the "Pause" button text to "Play"

That ensures that even if multiple clients are connected to the service, all actions are correctly synced across them.

**Comment by YurySolovyov** [comment]
Right, so we need to implement some kind of test client as you suggested, to listen to these events and which we can ask for current state.

**Comment by YurySolovyov** [comment]
I need this module as part of https://github.com/KeitIG/museeks/issues/93, maybe you can join our gitter channel and we can talk?

**Comment by emersion** [comment]
The problem is: which library should we use to write the test client? If we want to switch to the native implementation, it would be unfortunate to use the dbus bindings for tests. Maybe first write tests with the native implementation, and then switch the whole library to native?

**Comment by YurySolovyov** [comment]
> Maybe first write tests with the native implementation, and then switch the whole library to native?

+1 for that, we can also learn the library itself in the process

**Comment by emersion** [comment]
Okay, so I'll create a branch for that and give you push access to it, to be able to work collaboratively.

**Comment by acrisci** [comment]
We have an integration test suite now. Run with `npm run test`.
