### ISSUE TITLE
dbus commands all time out

### ISSUE THREAD

**Issue by timo** [emersion/mpris-service#9]
heya,

i've been trying out google play music desktop player (see also https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2321) and found that sending dbus commands manually would always give a timeout response.

is there something mpris-service can or should do to tell callers that things have succeeded instead of just letting it time out?

**Comment by emersion** [comment]
Thanks for reporting this bug! You're right, callbacks were never called.

Published as v1.1.3. ;-)
